#!/usr/bin/env bash

if pgrep -x "wlogout" > /dev/null; then
    pkill -x "wlogout"
    exit 0
fi

x_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .width')
y_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .height')
hypr_scale=$(hyprctl -j monitors | jq '.[] | select (.focused == true) | .scale' | sed 's/\.//')
hypr_border="$(hyprctl -j getoption decoration:rounding | jq '.int')"

export x_mgn=$(( x_mon * 35 / hypr_scale ))
export y_mgn=$(( y_mon * 25 / hypr_scale ))
export x_hvr=$(( x_mon * 32 / hypr_scale ))
export y_hvr=$(( y_mon * 20 / hypr_scale ))
export fntSize=$(( y_mon * 2 / 100 ))
export active_rad=$(( hypr_border * 5 ))
export button_rad=$(( hypr_border * 8 ))

css="$(envsubst < ~/.config/wlogout/style.css)"

wlogout -b 2 -c 0 -r 0 -m 0 --layout "${HOME}/.config/wlogout/layout" --css <(echo "${css}") --protocol layer-shell