console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
shell_integration = true

[palette]
  blue = '#89B4FA'
  crust = '#11111B'
  docker = 'p:sky'
  flamingo = '#F2CDCD'
  git = 'p:lavender'
  go = 'p:mauve'
  green = '#A6E3A1'
  haskell = 'p:mauve'
  lavender = '#B4BEFE'
  lua = 'p:mauve'
  mauve = '#CBA6F7'
  python = 'p:mauve'
  red = '#F38BA8'
  rust = 'p:mauve'
  sky = '#89DCEB'
  teal = '#94E2D5'
  text = '#CDD6F4'
  yellow = '#F9E2AF'

[transient_prompt]
  template = '❯ '
  foreground = 'p:green'
  foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:yellow'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '..'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }} '
    foreground = 'p:git'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_stash_count = false
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ' {{ .Context }} '
    foreground = 'p:docker'
    type = 'docker'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:go'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:haskell'
    type = 'haskell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:lua'
    type = 'lua'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ if .Venv }}venv/{{ end }}{{ .Full }}{{ end }} '
    foreground = 'p:python'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_default = false
      display_mode = 'context'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Full }}{{ end }} '
    foreground = 'p:rust'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '󰔟 {{ .FormattedMs }} '
    foreground = 'p:green'
    type = 'executiontime'
    style = 'plain'
    foreground_templates = ['{{ if .Code }}p:red{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'austin'
      threshold = 500.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = 'p:green'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
