# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#

$font = Nimbus Sans

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/.config/wallpaper
    blur_passes = 3
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big>$(date +%H)</big></b>"
    font_size = 113
    font_family = $font
    shadow_passes = 6
    shadow_size = 2

    position = 0, 280
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big>$(date +%M)</big></b>"
    font_size = 113
    font_family = $font
    shadow_passes = 6
    shadow_size = 2

    position = 0, 120
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big>$(date +'%A, %d %B')</big></b>"
    font_size = 22
    font_family = $font

    position = 0, 0
    halign = center
    valign = center
}

# Now playing
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/now-playing)"
    font_size = 18
    font_family = $font

    position = 100, 25
    halign = left
    valign = center
}

# Weather
label {
    monitor =
    text = cmd[update:18000000] echo "$(curl -s 'en.wttr.in?format=%c+%t' | tr -d '+')"
    font_size = 18
    font_family = $font

    position = 100, -25
    halign = left
    valign = center
}

# User
label {
    monitor =
    text = $USER
    font_size = 18
    font_family = $font

    position = 0, 180
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    inner_color = rgba(255, 255, 255, .75)

    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgb(243, 139, 168)

    fade_on_empty = false
    rounding = 24
    
    font_family = $font
    placeholder_text = Password...
    fail_text = $PAMFAIL

    hide_input = true

    position = 0, 100
    halign = center
    valign = bottom
}
